/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentRequest
 */
export interface CommentRequest {
    /**
     * 
     * @type {string}
     * @memberof CommentRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentRequest
     */
    content?: string;
}

/**
 * Check if a given object implements the CommentRequest interface.
 */
export function instanceOfCommentRequest(value: object): value is CommentRequest {
    return true;
}

export function CommentRequestFromJSON(json: any): CommentRequest {
    return CommentRequestFromJSONTyped(json, false);
}

export function CommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function CommentRequestToJSON(value?: CommentRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'content': value['content'],
    };
}

