/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DefaultPipingIntParameterRequest
 */
export interface DefaultPipingIntParameterRequest {
    /**
     * 
     * @type {number}
     * @memberof DefaultPipingIntParameterRequest
     */
    value?: number | null;
}

/**
 * Check if a given object implements the DefaultPipingIntParameterRequest interface.
 */
export function instanceOfDefaultPipingIntParameterRequest(value: object): value is DefaultPipingIntParameterRequest {
    return true;
}

export function DefaultPipingIntParameterRequestFromJSON(json: any): DefaultPipingIntParameterRequest {
    return DefaultPipingIntParameterRequestFromJSONTyped(json, false);
}

export function DefaultPipingIntParameterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefaultPipingIntParameterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function DefaultPipingIntParameterRequestToJSON(value?: DefaultPipingIntParameterRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'value': value['value'],
    };
}

