/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DefaultPipingStrParameterRequest
 */
export interface DefaultPipingStrParameterRequest {
    /**
     * 
     * @type {string}
     * @memberof DefaultPipingStrParameterRequest
     */
    value?: string | null;
}

/**
 * Check if a given object implements the DefaultPipingStrParameterRequest interface.
 */
export function instanceOfDefaultPipingStrParameterRequest(value: object): value is DefaultPipingStrParameterRequest {
    return true;
}

export function DefaultPipingStrParameterRequestFromJSON(json: any): DefaultPipingStrParameterRequest {
    return DefaultPipingStrParameterRequestFromJSONTyped(json, false);
}

export function DefaultPipingStrParameterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefaultPipingStrParameterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function DefaultPipingStrParameterRequestToJSON(value?: DefaultPipingStrParameterRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'value': value['value'],
    };
}

