/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DefaultPipingFloatParameterRequest
 */
export interface DefaultPipingFloatParameterRequest {
    /**
     * 
     * @type {number}
     * @memberof DefaultPipingFloatParameterRequest
     */
    value?: number | null;
}

/**
 * Check if a given object implements the DefaultPipingFloatParameterRequest interface.
 */
export function instanceOfDefaultPipingFloatParameterRequest(value: object): value is DefaultPipingFloatParameterRequest {
    return true;
}

export function DefaultPipingFloatParameterRequestFromJSON(json: any): DefaultPipingFloatParameterRequest {
    return DefaultPipingFloatParameterRequestFromJSONTyped(json, false);
}

export function DefaultPipingFloatParameterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefaultPipingFloatParameterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function DefaultPipingFloatParameterRequestToJSON(value?: DefaultPipingFloatParameterRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'value': value['value'],
    };
}

