/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedRequest
 */
export interface FeedRequest {
    /**
     * 
     * @type {string}
     * @memberof FeedRequest
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FeedRequest
     */
    _public?: boolean;
}

/**
 * Check if a given object implements the FeedRequest interface.
 */
export function instanceOfFeedRequest(value: object): value is FeedRequest {
    return true;
}

export function FeedRequestFromJSON(json: any): FeedRequest {
    return FeedRequestFromJSONTyped(json, false);
}

export function FeedRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        '_public': json['public'] == null ? undefined : json['public'],
    };
}

export function FeedRequestToJSON(value?: FeedRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'public': value['_public'],
    };
}

