/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileBrowserFolder
 */
export interface FileBrowserFolder {
    /**
     * 
     * @type {string}
     * @memberof FileBrowserFolder
     */
    readonly url: string;
    /**
     * 
     * @type {number}
     * @memberof FileBrowserFolder
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof FileBrowserFolder
     */
    readonly creationDate: Date;
    /**
     * 
     * @type {string}
     * @memberof FileBrowserFolder
     */
    path?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FileBrowserFolder
     */
    _public?: boolean;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof FileBrowserFolder
     */
    readonly ownerUsername: string;
    /**
     * 
     * @type {string}
     * @memberof FileBrowserFolder
     */
    readonly parent: string;
    /**
     * 
     * @type {string}
     * @memberof FileBrowserFolder
     */
    readonly children: string;
    /**
     * 
     * @type {string}
     * @memberof FileBrowserFolder
     */
    readonly files: string;
    /**
     * 
     * @type {string}
     * @memberof FileBrowserFolder
     */
    readonly linkFiles: string;
    /**
     * 
     * @type {string}
     * @memberof FileBrowserFolder
     */
    readonly groupPermissions: string;
    /**
     * 
     * @type {string}
     * @memberof FileBrowserFolder
     */
    readonly userPermissions: string;
    /**
     * 
     * @type {string}
     * @memberof FileBrowserFolder
     */
    readonly owner: string;
}

/**
 * Check if a given object implements the FileBrowserFolder interface.
 */
export function instanceOfFileBrowserFolder(value: object): value is FileBrowserFolder {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('creationDate' in value) || value['creationDate'] === undefined) return false;
    if (!('ownerUsername' in value) || value['ownerUsername'] === undefined) return false;
    if (!('parent' in value) || value['parent'] === undefined) return false;
    if (!('children' in value) || value['children'] === undefined) return false;
    if (!('files' in value) || value['files'] === undefined) return false;
    if (!('linkFiles' in value) || value['linkFiles'] === undefined) return false;
    if (!('groupPermissions' in value) || value['groupPermissions'] === undefined) return false;
    if (!('userPermissions' in value) || value['userPermissions'] === undefined) return false;
    if (!('owner' in value) || value['owner'] === undefined) return false;
    return true;
}

export function FileBrowserFolderFromJSON(json: any): FileBrowserFolder {
    return FileBrowserFolderFromJSONTyped(json, false);
}

export function FileBrowserFolderFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileBrowserFolder {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'id': json['id'],
        'creationDate': (new Date(json['creation_date'])),
        'path': json['path'] == null ? undefined : json['path'],
        '_public': json['public'] == null ? undefined : json['public'],
        'ownerUsername': json['owner_username'],
        'parent': json['parent'],
        'children': json['children'],
        'files': json['files'],
        'linkFiles': json['link_files'],
        'groupPermissions': json['group_permissions'],
        'userPermissions': json['user_permissions'],
        'owner': json['owner'],
    };
}

export function FileBrowserFolderToJSON(value?: Omit<FileBrowserFolder, 'url'|'id'|'creation_date'|'owner_username'|'parent'|'children'|'files'|'link_files'|'group_permissions'|'user_permissions'|'owner'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'path': value['path'],
        'public': value['_public'],
    };
}

