/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PermissionEnum } from './PermissionEnum';
import {
    PermissionEnumFromJSON,
    PermissionEnumFromJSONTyped,
    PermissionEnumToJSON,
} from './PermissionEnum';

/**
 * 
 * @export
 * @interface FileBrowserLinkFileGroupPermission
 */
export interface FileBrowserLinkFileGroupPermission {
    /**
     * 
     * @type {string}
     * @memberof FileBrowserLinkFileGroupPermission
     */
    readonly url: string;
    /**
     * 
     * @type {number}
     * @memberof FileBrowserLinkFileGroupPermission
     */
    readonly id: number;
    /**
     * 
     * @type {PermissionEnum}
     * @memberof FileBrowserLinkFileGroupPermission
     */
    permission?: PermissionEnum;
    /**
     * 
     * @type {number}
     * @memberof FileBrowserLinkFileGroupPermission
     */
    readonly linkFileId: number;
    /**
     * 
     * @type {string}
     * @memberof FileBrowserLinkFileGroupPermission
     */
    readonly linkFileFname: string;
    /**
     * 
     * @type {number}
     * @memberof FileBrowserLinkFileGroupPermission
     */
    readonly groupId: number;
    /**
     * 
     * @type {string}
     * @memberof FileBrowserLinkFileGroupPermission
     */
    readonly groupName: string;
    /**
     * 
     * @type {string}
     * @memberof FileBrowserLinkFileGroupPermission
     */
    readonly linkFile: string;
    /**
     * 
     * @type {string}
     * @memberof FileBrowserLinkFileGroupPermission
     */
    readonly group: string;
}



/**
 * Check if a given object implements the FileBrowserLinkFileGroupPermission interface.
 */
export function instanceOfFileBrowserLinkFileGroupPermission(value: object): value is FileBrowserLinkFileGroupPermission {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('linkFileId' in value) || value['linkFileId'] === undefined) return false;
    if (!('linkFileFname' in value) || value['linkFileFname'] === undefined) return false;
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    if (!('groupName' in value) || value['groupName'] === undefined) return false;
    if (!('linkFile' in value) || value['linkFile'] === undefined) return false;
    if (!('group' in value) || value['group'] === undefined) return false;
    return true;
}

export function FileBrowserLinkFileGroupPermissionFromJSON(json: any): FileBrowserLinkFileGroupPermission {
    return FileBrowserLinkFileGroupPermissionFromJSONTyped(json, false);
}

export function FileBrowserLinkFileGroupPermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileBrowserLinkFileGroupPermission {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'id': json['id'],
        'permission': json['permission'] == null ? undefined : PermissionEnumFromJSON(json['permission']),
        'linkFileId': json['link_file_id'],
        'linkFileFname': json['link_file_fname'],
        'groupId': json['group_id'],
        'groupName': json['group_name'],
        'linkFile': json['link_file'],
        'group': json['group'],
    };
}

export function FileBrowserLinkFileGroupPermissionToJSON(value?: Omit<FileBrowserLinkFileGroupPermission, 'url'|'id'|'link_file_id'|'link_file_fname'|'group_id'|'group_name'|'link_file'|'group'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'permission': PermissionEnumToJSON(value['permission']),
    };
}

