/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PermissionEnum } from './PermissionEnum';
import {
    PermissionEnumFromJSON,
    PermissionEnumFromJSONTyped,
    PermissionEnumToJSON,
} from './PermissionEnum';

/**
 * 
 * @export
 * @interface FileBrowserFileUserPermission
 */
export interface FileBrowserFileUserPermission {
    /**
     * 
     * @type {string}
     * @memberof FileBrowserFileUserPermission
     */
    readonly url: string;
    /**
     * 
     * @type {number}
     * @memberof FileBrowserFileUserPermission
     */
    readonly id: number;
    /**
     * 
     * @type {PermissionEnum}
     * @memberof FileBrowserFileUserPermission
     */
    permission?: PermissionEnum;
    /**
     * 
     * @type {number}
     * @memberof FileBrowserFileUserPermission
     */
    readonly fileId: number;
    /**
     * 
     * @type {string}
     * @memberof FileBrowserFileUserPermission
     */
    readonly fileFname: string;
    /**
     * 
     * @type {number}
     * @memberof FileBrowserFileUserPermission
     */
    readonly userId: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof FileBrowserFileUserPermission
     */
    readonly userUsername: string;
    /**
     * 
     * @type {string}
     * @memberof FileBrowserFileUserPermission
     */
    readonly file: string;
    /**
     * 
     * @type {string}
     * @memberof FileBrowserFileUserPermission
     */
    readonly user: string;
}



/**
 * Check if a given object implements the FileBrowserFileUserPermission interface.
 */
export function instanceOfFileBrowserFileUserPermission(value: object): value is FileBrowserFileUserPermission {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    if (!('fileFname' in value) || value['fileFname'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('userUsername' in value) || value['userUsername'] === undefined) return false;
    if (!('file' in value) || value['file'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function FileBrowserFileUserPermissionFromJSON(json: any): FileBrowserFileUserPermission {
    return FileBrowserFileUserPermissionFromJSONTyped(json, false);
}

export function FileBrowserFileUserPermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileBrowserFileUserPermission {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'id': json['id'],
        'permission': json['permission'] == null ? undefined : PermissionEnumFromJSON(json['permission']),
        'fileId': json['file_id'],
        'fileFname': json['file_fname'],
        'userId': json['user_id'],
        'userUsername': json['user_username'],
        'file': json['file'],
        'user': json['user'],
    };
}

export function FileBrowserFileUserPermissionToJSON(value?: Omit<FileBrowserFileUserPermission, 'url'|'id'|'file_id'|'file_fname'|'user_id'|'user_username'|'file'|'user'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'permission': PermissionEnumToJSON(value['permission']),
    };
}

