/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileDownloadTokenRequest
 */
export interface FileDownloadTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof FileDownloadTokenRequest
     */
    token?: string;
}

/**
 * Check if a given object implements the FileDownloadTokenRequest interface.
 */
export function instanceOfFileDownloadTokenRequest(value: object): value is FileDownloadTokenRequest {
    return true;
}

export function FileDownloadTokenRequestFromJSON(json: any): FileDownloadTokenRequest {
    return FileDownloadTokenRequestFromJSONTyped(json, false);
}

export function FileDownloadTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileDownloadTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function FileDownloadTokenRequestToJSON(value?: FileDownloadTokenRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'token': value['token'],
    };
}

