/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileBrowserLinkFileRequest
 */
export interface FileBrowserLinkFileRequest {
    /**
     * 
     * @type {string}
     * @memberof FileBrowserLinkFileRequest
     */
    path?: string;
    /**
     * 
     * @type {Blob}
     * @memberof FileBrowserLinkFileRequest
     */
    fname?: Blob;
    /**
     * 
     * @type {boolean}
     * @memberof FileBrowserLinkFileRequest
     */
    _public?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FileBrowserLinkFileRequest
     */
    newLinkFilePath?: string;
}

/**
 * Check if a given object implements the FileBrowserLinkFileRequest interface.
 */
export function instanceOfFileBrowserLinkFileRequest(value: object): value is FileBrowserLinkFileRequest {
    return true;
}

export function FileBrowserLinkFileRequestFromJSON(json: any): FileBrowserLinkFileRequest {
    return FileBrowserLinkFileRequestFromJSONTyped(json, false);
}

export function FileBrowserLinkFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileBrowserLinkFileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'] == null ? undefined : json['path'],
        'fname': json['fname'] == null ? undefined : json['fname'],
        '_public': json['public'] == null ? undefined : json['public'],
        'newLinkFilePath': json['new_link_file_path'] == null ? undefined : json['new_link_file_path'],
    };
}

export function FileBrowserLinkFileRequestToJSON(value?: FileBrowserLinkFileRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'path': value['path'],
        'fname': value['fname'],
        'public': value['_public'],
        'new_link_file_path': value['newLinkFilePath'],
    };
}

