/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PermissionEnum } from './PermissionEnum';
import {
    PermissionEnumFromJSON,
    PermissionEnumFromJSONTyped,
    PermissionEnumToJSON,
} from './PermissionEnum';

/**
 * 
 * @export
 * @interface FileBrowserFolderGroupPermissionRequest
 */
export interface FileBrowserFolderGroupPermissionRequest {
    /**
     * 
     * @type {PermissionEnum}
     * @memberof FileBrowserFolderGroupPermissionRequest
     */
    permission?: PermissionEnum;
    /**
     * 
     * @type {string}
     * @memberof FileBrowserFolderGroupPermissionRequest
     */
    grpName?: string;
}



/**
 * Check if a given object implements the FileBrowserFolderGroupPermissionRequest interface.
 */
export function instanceOfFileBrowserFolderGroupPermissionRequest(value: object): value is FileBrowserFolderGroupPermissionRequest {
    return true;
}

export function FileBrowserFolderGroupPermissionRequestFromJSON(json: any): FileBrowserFolderGroupPermissionRequest {
    return FileBrowserFolderGroupPermissionRequestFromJSONTyped(json, false);
}

export function FileBrowserFolderGroupPermissionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileBrowserFolderGroupPermissionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'permission': json['permission'] == null ? undefined : PermissionEnumFromJSON(json['permission']),
        'grpName': json['grp_name'] == null ? undefined : json['grp_name'],
    };
}

export function FileBrowserFolderGroupPermissionRequestToJSON(value?: FileBrowserFolderGroupPermissionRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'permission': PermissionEnumToJSON(value['permission']),
        'grp_name': value['grpName'],
    };
}

