/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupUserRequest
 */
export interface GroupUserRequest {
    /**
     * 
     * @type {string}
     * @memberof GroupUserRequest
     */
    username: string;
}

/**
 * Check if a given object implements the GroupUserRequest interface.
 */
export function instanceOfGroupUserRequest(value: object): value is GroupUserRequest {
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function GroupUserRequestFromJSON(json: any): GroupUserRequest {
    return GroupUserRequestFromJSONTyped(json, false);
}

export function GroupUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
    };
}

export function GroupUserRequestToJSON(value?: GroupUserRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'username': value['username'],
    };
}

