/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PACSFile
 */
export interface PACSFile {
    /**
     * 
     * @type {string}
     * @memberof PACSFile
     */
    readonly url: string;
    /**
     * 
     * @type {number}
     * @memberof PACSFile
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof PACSFile
     */
    readonly creationDate: Date;
    /**
     * 
     * @type {string}
     * @memberof PACSFile
     */
    fname: string;
    /**
     * 
     * @type {string}
     * @memberof PACSFile
     */
    readonly fsize: string;
    /**
     * 
     * @type {boolean}
     * @memberof PACSFile
     */
    _public?: boolean;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof PACSFile
     */
    readonly ownerUsername: string;
    /**
     * 
     * @type {string}
     * @memberof PACSFile
     */
    readonly fileResource: string;
    /**
     * 
     * @type {string}
     * @memberof PACSFile
     */
    readonly parentFolder: string;
    /**
     * 
     * @type {string}
     * @memberof PACSFile
     */
    readonly owner: string;
}

/**
 * Check if a given object implements the PACSFile interface.
 */
export function instanceOfPACSFile(value: object): value is PACSFile {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('creationDate' in value) || value['creationDate'] === undefined) return false;
    if (!('fname' in value) || value['fname'] === undefined) return false;
    if (!('fsize' in value) || value['fsize'] === undefined) return false;
    if (!('ownerUsername' in value) || value['ownerUsername'] === undefined) return false;
    if (!('fileResource' in value) || value['fileResource'] === undefined) return false;
    if (!('parentFolder' in value) || value['parentFolder'] === undefined) return false;
    if (!('owner' in value) || value['owner'] === undefined) return false;
    return true;
}

export function PACSFileFromJSON(json: any): PACSFile {
    return PACSFileFromJSONTyped(json, false);
}

export function PACSFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): PACSFile {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'id': json['id'],
        'creationDate': (new Date(json['creation_date'])),
        'fname': json['fname'],
        'fsize': json['fsize'],
        '_public': json['public'] == null ? undefined : json['public'],
        'ownerUsername': json['owner_username'],
        'fileResource': json['file_resource'],
        'parentFolder': json['parent_folder'],
        'owner': json['owner'],
    };
}

export function PACSFileToJSON(value?: Omit<PACSFile, 'url'|'id'|'creation_date'|'fsize'|'owner_username'|'file_resource'|'parent_folder'|'owner'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'fname': value['fname'],
        'public': value['_public'],
    };
}

