/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Comment } from './Comment';
import {
    CommentFromJSON,
    CommentFromJSONTyped,
    CommentToJSON,
} from './Comment';

/**
 * 
 * @export
 * @interface PaginatedCommentList
 */
export interface PaginatedCommentList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedCommentList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCommentList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCommentList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Comment>}
     * @memberof PaginatedCommentList
     */
    results?: Array<Comment>;
}

/**
 * Check if a given object implements the PaginatedCommentList interface.
 */
export function instanceOfPaginatedCommentList(value: object): value is PaginatedCommentList {
    return true;
}

export function PaginatedCommentListFromJSON(json: any): PaginatedCommentList {
    return PaginatedCommentListFromJSONTyped(json, false);
}

export function PaginatedCommentListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedCommentList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(CommentFromJSON)),
    };
}

export function PaginatedCommentListToJSON(value?: PaginatedCommentList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(CommentToJSON)),
    };
}

