/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeedUserPermission } from './FeedUserPermission';
import {
    FeedUserPermissionFromJSON,
    FeedUserPermissionFromJSONTyped,
    FeedUserPermissionToJSON,
} from './FeedUserPermission';

/**
 * 
 * @export
 * @interface PaginatedFeedUserPermissionList
 */
export interface PaginatedFeedUserPermissionList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedFeedUserPermissionList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedFeedUserPermissionList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedFeedUserPermissionList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<FeedUserPermission>}
     * @memberof PaginatedFeedUserPermissionList
     */
    results?: Array<FeedUserPermission>;
}

/**
 * Check if a given object implements the PaginatedFeedUserPermissionList interface.
 */
export function instanceOfPaginatedFeedUserPermissionList(value: object): value is PaginatedFeedUserPermissionList {
    return true;
}

export function PaginatedFeedUserPermissionListFromJSON(json: any): PaginatedFeedUserPermissionList {
    return PaginatedFeedUserPermissionListFromJSONTyped(json, false);
}

export function PaginatedFeedUserPermissionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedFeedUserPermissionList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(FeedUserPermissionFromJSON)),
    };
}

export function PaginatedFeedUserPermissionListToJSON(value?: PaginatedFeedUserPermissionList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(FeedUserPermissionToJSON)),
    };
}

