/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileBrowserFile } from './FileBrowserFile';
import {
    FileBrowserFileFromJSON,
    FileBrowserFileFromJSONTyped,
    FileBrowserFileToJSON,
} from './FileBrowserFile';

/**
 * 
 * @export
 * @interface PaginatedFileBrowserFileList
 */
export interface PaginatedFileBrowserFileList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedFileBrowserFileList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedFileBrowserFileList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedFileBrowserFileList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<FileBrowserFile>}
     * @memberof PaginatedFileBrowserFileList
     */
    results?: Array<FileBrowserFile>;
}

/**
 * Check if a given object implements the PaginatedFileBrowserFileList interface.
 */
export function instanceOfPaginatedFileBrowserFileList(value: object): value is PaginatedFileBrowserFileList {
    return true;
}

export function PaginatedFileBrowserFileListFromJSON(json: any): PaginatedFileBrowserFileList {
    return PaginatedFileBrowserFileListFromJSONTyped(json, false);
}

export function PaginatedFileBrowserFileListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedFileBrowserFileList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(FileBrowserFileFromJSON)),
    };
}

export function PaginatedFileBrowserFileListToJSON(value?: PaginatedFileBrowserFileList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(FileBrowserFileToJSON)),
    };
}

