/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ComputeResource } from './ComputeResource';
import {
    ComputeResourceFromJSON,
    ComputeResourceFromJSONTyped,
    ComputeResourceToJSON,
} from './ComputeResource';

/**
 * 
 * @export
 * @interface PaginatedComputeResourceList
 */
export interface PaginatedComputeResourceList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedComputeResourceList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedComputeResourceList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedComputeResourceList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<ComputeResource>}
     * @memberof PaginatedComputeResourceList
     */
    results?: Array<ComputeResource>;
}

/**
 * Check if a given object implements the PaginatedComputeResourceList interface.
 */
export function instanceOfPaginatedComputeResourceList(value: object): value is PaginatedComputeResourceList {
    return true;
}

export function PaginatedComputeResourceListFromJSON(json: any): PaginatedComputeResourceList {
    return PaginatedComputeResourceListFromJSONTyped(json, false);
}

export function PaginatedComputeResourceListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedComputeResourceList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(ComputeResourceFromJSON)),
    };
}

export function PaginatedComputeResourceListToJSON(value?: PaginatedComputeResourceList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(ComputeResourceToJSON)),
    };
}

