/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pipeline } from './Pipeline';
import {
    PipelineFromJSON,
    PipelineFromJSONTyped,
    PipelineToJSON,
} from './Pipeline';

/**
 * 
 * @export
 * @interface PaginatedPipelineList
 */
export interface PaginatedPipelineList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedPipelineList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPipelineList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPipelineList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Pipeline>}
     * @memberof PaginatedPipelineList
     */
    results?: Array<Pipeline>;
}

/**
 * Check if a given object implements the PaginatedPipelineList interface.
 */
export function instanceOfPaginatedPipelineList(value: object): value is PaginatedPipelineList {
    return true;
}

export function PaginatedPipelineListFromJSON(json: any): PaginatedPipelineList {
    return PaginatedPipelineListFromJSONTyped(json, false);
}

export function PaginatedPipelineListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedPipelineList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(PipelineFromJSON)),
    };
}

export function PaginatedPipelineListToJSON(value?: PaginatedPipelineList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(PipelineToJSON)),
    };
}

