/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PluginInstance } from './PluginInstance';
import {
    PluginInstanceFromJSON,
    PluginInstanceFromJSONTyped,
    PluginInstanceToJSON,
} from './PluginInstance';

/**
 * 
 * @export
 * @interface PaginatedPluginInstanceList
 */
export interface PaginatedPluginInstanceList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedPluginInstanceList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPluginInstanceList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPluginInstanceList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<PluginInstance>}
     * @memberof PaginatedPluginInstanceList
     */
    results?: Array<PluginInstance>;
}

/**
 * Check if a given object implements the PaginatedPluginInstanceList interface.
 */
export function instanceOfPaginatedPluginInstanceList(value: object): value is PaginatedPluginInstanceList {
    return true;
}

export function PaginatedPluginInstanceListFromJSON(json: any): PaginatedPluginInstanceList {
    return PaginatedPluginInstanceListFromJSONTyped(json, false);
}

export function PaginatedPluginInstanceListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedPluginInstanceList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(PluginInstanceFromJSON)),
    };
}

export function PaginatedPluginInstanceListToJSON(value?: PaginatedPluginInstanceList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(PluginInstanceToJSON)),
    };
}

