/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Feed } from './Feed';
import {
    FeedFromJSON,
    FeedFromJSONTyped,
    FeedToJSON,
} from './Feed';

/**
 * 
 * @export
 * @interface PaginatedFeedList
 */
export interface PaginatedFeedList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedFeedList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedFeedList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedFeedList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Feed>}
     * @memberof PaginatedFeedList
     */
    results?: Array<Feed>;
}

/**
 * Check if a given object implements the PaginatedFeedList interface.
 */
export function instanceOfPaginatedFeedList(value: object): value is PaginatedFeedList {
    return true;
}

export function PaginatedFeedListFromJSON(json: any): PaginatedFeedList {
    return PaginatedFeedListFromJSONTyped(json, false);
}

export function PaginatedFeedListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedFeedList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(FeedFromJSON)),
    };
}

export function PaginatedFeedListToJSON(value?: PaginatedFeedList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(FeedToJSON)),
    };
}

