/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PACSFile } from './PACSFile';
import {
    PACSFileFromJSON,
    PACSFileFromJSONTyped,
    PACSFileToJSON,
} from './PACSFile';

/**
 * 
 * @export
 * @interface PaginatedPACSFileList
 */
export interface PaginatedPACSFileList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedPACSFileList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPACSFileList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPACSFileList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<PACSFile>}
     * @memberof PaginatedPACSFileList
     */
    results?: Array<PACSFile>;
}

/**
 * Check if a given object implements the PaginatedPACSFileList interface.
 */
export function instanceOfPaginatedPACSFileList(value: object): value is PaginatedPACSFileList {
    return true;
}

export function PaginatedPACSFileListFromJSON(json: any): PaginatedPACSFileList {
    return PaginatedPACSFileListFromJSONTyped(json, false);
}

export function PaginatedPACSFileListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedPACSFileList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(PACSFileFromJSON)),
    };
}

export function PaginatedPACSFileListToJSON(value?: PaginatedPACSFileList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(PACSFileToJSON)),
    };
}

