/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PACSSeries } from './PACSSeries';
import {
    PACSSeriesFromJSON,
    PACSSeriesFromJSONTyped,
    PACSSeriesToJSON,
} from './PACSSeries';

/**
 * 
 * @export
 * @interface PaginatedPACSSeriesList
 */
export interface PaginatedPACSSeriesList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedPACSSeriesList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPACSSeriesList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPACSSeriesList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<PACSSeries>}
     * @memberof PaginatedPACSSeriesList
     */
    results?: Array<PACSSeries>;
}

/**
 * Check if a given object implements the PaginatedPACSSeriesList interface.
 */
export function instanceOfPaginatedPACSSeriesList(value: object): value is PaginatedPACSSeriesList {
    return true;
}

export function PaginatedPACSSeriesListFromJSON(json: any): PaginatedPACSSeriesList {
    return PaginatedPACSSeriesListFromJSONTyped(json, false);
}

export function PaginatedPACSSeriesListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedPACSSeriesList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(PACSSeriesFromJSON)),
    };
}

export function PaginatedPACSSeriesListToJSON(value?: PaginatedPACSSeriesList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(PACSSeriesToJSON)),
    };
}

