/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileBrowserLinkFileGroupPermission } from './FileBrowserLinkFileGroupPermission';
import {
    FileBrowserLinkFileGroupPermissionFromJSON,
    FileBrowserLinkFileGroupPermissionFromJSONTyped,
    FileBrowserLinkFileGroupPermissionToJSON,
} from './FileBrowserLinkFileGroupPermission';

/**
 * 
 * @export
 * @interface PaginatedFileBrowserLinkFileGroupPermissionList
 */
export interface PaginatedFileBrowserLinkFileGroupPermissionList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedFileBrowserLinkFileGroupPermissionList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedFileBrowserLinkFileGroupPermissionList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedFileBrowserLinkFileGroupPermissionList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<FileBrowserLinkFileGroupPermission>}
     * @memberof PaginatedFileBrowserLinkFileGroupPermissionList
     */
    results?: Array<FileBrowserLinkFileGroupPermission>;
}

/**
 * Check if a given object implements the PaginatedFileBrowserLinkFileGroupPermissionList interface.
 */
export function instanceOfPaginatedFileBrowserLinkFileGroupPermissionList(value: object): value is PaginatedFileBrowserLinkFileGroupPermissionList {
    return true;
}

export function PaginatedFileBrowserLinkFileGroupPermissionListFromJSON(json: any): PaginatedFileBrowserLinkFileGroupPermissionList {
    return PaginatedFileBrowserLinkFileGroupPermissionListFromJSONTyped(json, false);
}

export function PaginatedFileBrowserLinkFileGroupPermissionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedFileBrowserLinkFileGroupPermissionList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(FileBrowserLinkFileGroupPermissionFromJSON)),
    };
}

export function PaginatedFileBrowserLinkFileGroupPermissionListToJSON(value?: PaginatedFileBrowserLinkFileGroupPermissionList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(FileBrowserLinkFileGroupPermissionToJSON)),
    };
}

