/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Group } from './Group';
import {
    GroupFromJSON,
    GroupFromJSONTyped,
    GroupToJSON,
} from './Group';

/**
 * 
 * @export
 * @interface PaginatedGroupList
 */
export interface PaginatedGroupList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedGroupList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedGroupList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedGroupList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Group>}
     * @memberof PaginatedGroupList
     */
    results?: Array<Group>;
}

/**
 * Check if a given object implements the PaginatedGroupList interface.
 */
export function instanceOfPaginatedGroupList(value: object): value is PaginatedGroupList {
    return true;
}

export function PaginatedGroupListFromJSON(json: any): PaginatedGroupList {
    return PaginatedGroupListFromJSONTyped(json, false);
}

export function PaginatedGroupListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedGroupList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(GroupFromJSON)),
    };
}

export function PaginatedGroupListToJSON(value?: PaginatedGroupList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(GroupToJSON)),
    };
}

