/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PluginInstanceSplit } from './PluginInstanceSplit';
import {
    PluginInstanceSplitFromJSON,
    PluginInstanceSplitFromJSONTyped,
    PluginInstanceSplitToJSON,
} from './PluginInstanceSplit';

/**
 * 
 * @export
 * @interface PaginatedPluginInstanceSplitList
 */
export interface PaginatedPluginInstanceSplitList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedPluginInstanceSplitList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPluginInstanceSplitList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPluginInstanceSplitList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<PluginInstanceSplit>}
     * @memberof PaginatedPluginInstanceSplitList
     */
    results?: Array<PluginInstanceSplit>;
}

/**
 * Check if a given object implements the PaginatedPluginInstanceSplitList interface.
 */
export function instanceOfPaginatedPluginInstanceSplitList(value: object): value is PaginatedPluginInstanceSplitList {
    return true;
}

export function PaginatedPluginInstanceSplitListFromJSON(json: any): PaginatedPluginInstanceSplitList {
    return PaginatedPluginInstanceSplitListFromJSONTyped(json, false);
}

export function PaginatedPluginInstanceSplitListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedPluginInstanceSplitList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(PluginInstanceSplitFromJSON)),
    };
}

export function PaginatedPluginInstanceSplitListToJSON(value?: PaginatedPluginInstanceSplitList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(PluginInstanceSplitToJSON)),
    };
}

