/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PluginParameter } from './PluginParameter';
import {
    PluginParameterFromJSON,
    PluginParameterFromJSONTyped,
    PluginParameterToJSON,
} from './PluginParameter';

/**
 * 
 * @export
 * @interface PaginatedPluginParameterList
 */
export interface PaginatedPluginParameterList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedPluginParameterList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPluginParameterList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPluginParameterList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<PluginParameter>}
     * @memberof PaginatedPluginParameterList
     */
    results?: Array<PluginParameter>;
}

/**
 * Check if a given object implements the PaginatedPluginParameterList interface.
 */
export function instanceOfPaginatedPluginParameterList(value: object): value is PaginatedPluginParameterList {
    return true;
}

export function PaginatedPluginParameterListFromJSON(json: any): PaginatedPluginParameterList {
    return PaginatedPluginParameterListFromJSONTyped(json, false);
}

export function PaginatedPluginParameterListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedPluginParameterList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(PluginParameterFromJSON)),
    };
}

export function PaginatedPluginParameterListToJSON(value?: PaginatedPluginParameterList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(PluginParameterToJSON)),
    };
}

