/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PluginAdmin } from './PluginAdmin';
import {
    PluginAdminFromJSON,
    PluginAdminFromJSONTyped,
    PluginAdminToJSON,
} from './PluginAdmin';

/**
 * 
 * @export
 * @interface PaginatedPluginAdminList
 */
export interface PaginatedPluginAdminList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedPluginAdminList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPluginAdminList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPluginAdminList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<PluginAdmin>}
     * @memberof PaginatedPluginAdminList
     */
    results?: Array<PluginAdmin>;
}

/**
 * Check if a given object implements the PaginatedPluginAdminList interface.
 */
export function instanceOfPaginatedPluginAdminList(value: object): value is PaginatedPluginAdminList {
    return true;
}

export function PaginatedPluginAdminListFromJSON(json: any): PaginatedPluginAdminList {
    return PaginatedPluginAdminListFromJSONTyped(json, false);
}

export function PaginatedPluginAdminListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedPluginAdminList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(PluginAdminFromJSON)),
    };
}

export function PaginatedPluginAdminListToJSON(value?: PaginatedPluginAdminList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(PluginAdminToJSON)),
    };
}

