/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Tag } from './Tag';
import {
    TagFromJSON,
    TagFromJSONTyped,
    TagToJSON,
} from './Tag';

/**
 * 
 * @export
 * @interface PaginatedTagList
 */
export interface PaginatedTagList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedTagList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTagList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTagList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Tag>}
     * @memberof PaginatedTagList
     */
    results?: Array<Tag>;
}

/**
 * Check if a given object implements the PaginatedTagList interface.
 */
export function instanceOfPaginatedTagList(value: object): value is PaginatedTagList {
    return true;
}

export function PaginatedTagListFromJSON(json: any): PaginatedTagList {
    return PaginatedTagListFromJSONTyped(json, false);
}

export function PaginatedTagListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedTagList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(TagFromJSON)),
    };
}

export function PaginatedTagListToJSON(value?: PaginatedTagList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(TagToJSON)),
    };
}

