/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Plugin } from './Plugin';
import {
    PluginFromJSON,
    PluginFromJSONTyped,
    PluginToJSON,
} from './Plugin';

/**
 * 
 * @export
 * @interface PaginatedPluginList
 */
export interface PaginatedPluginList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedPluginList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPluginList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPluginList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Plugin>}
     * @memberof PaginatedPluginList
     */
    results?: Array<Plugin>;
}

/**
 * Check if a given object implements the PaginatedPluginList interface.
 */
export function instanceOfPaginatedPluginList(value: object): value is PaginatedPluginList {
    return true;
}

export function PaginatedPluginListFromJSON(json: any): PaginatedPluginList {
    return PaginatedPluginListFromJSONTyped(json, false);
}

export function PaginatedPluginListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedPluginList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(PluginFromJSON)),
    };
}

export function PaginatedPluginListToJSON(value?: PaginatedPluginList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(PluginToJSON)),
    };
}

