/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PluginMeta } from './PluginMeta';
import {
    PluginMetaFromJSON,
    PluginMetaFromJSONTyped,
    PluginMetaToJSON,
} from './PluginMeta';

/**
 * 
 * @export
 * @interface PaginatedPluginMetaList
 */
export interface PaginatedPluginMetaList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedPluginMetaList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPluginMetaList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPluginMetaList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<PluginMeta>}
     * @memberof PaginatedPluginMetaList
     */
    results?: Array<PluginMeta>;
}

/**
 * Check if a given object implements the PaginatedPluginMetaList interface.
 */
export function instanceOfPaginatedPluginMetaList(value: object): value is PaginatedPluginMetaList {
    return true;
}

export function PaginatedPluginMetaListFromJSON(json: any): PaginatedPluginMetaList {
    return PaginatedPluginMetaListFromJSONTyped(json, false);
}

export function PaginatedPluginMetaListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedPluginMetaList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(PluginMetaFromJSON)),
    };
}

export function PaginatedPluginMetaListToJSON(value?: PaginatedPluginMetaList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(PluginMetaToJSON)),
    };
}

