/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupUser } from './GroupUser';
import {
    GroupUserFromJSON,
    GroupUserFromJSONTyped,
    GroupUserToJSON,
} from './GroupUser';

/**
 * 
 * @export
 * @interface PaginatedGroupUserList
 */
export interface PaginatedGroupUserList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedGroupUserList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedGroupUserList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedGroupUserList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<GroupUser>}
     * @memberof PaginatedGroupUserList
     */
    results?: Array<GroupUser>;
}

/**
 * Check if a given object implements the PaginatedGroupUserList interface.
 */
export function instanceOfPaginatedGroupUserList(value: object): value is PaginatedGroupUserList {
    return true;
}

export function PaginatedGroupUserListFromJSON(json: any): PaginatedGroupUserList {
    return PaginatedGroupUserListFromJSONTyped(json, false);
}

export function PaginatedGroupUserListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedGroupUserList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(GroupUserFromJSON)),
    };
}

export function PaginatedGroupUserListToJSON(value?: PaginatedGroupUserList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(GroupUserToJSON)),
    };
}

