/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GenericParameter } from './GenericParameter';
import {
    GenericParameterFromJSON,
    GenericParameterFromJSONTyped,
    GenericParameterToJSON,
} from './GenericParameter';

/**
 * 
 * @export
 * @interface PaginatedGenericParameterList
 */
export interface PaginatedGenericParameterList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedGenericParameterList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedGenericParameterList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedGenericParameterList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<GenericParameter>}
     * @memberof PaginatedGenericParameterList
     */
    results?: Array<GenericParameter>;
}

/**
 * Check if a given object implements the PaginatedGenericParameterList interface.
 */
export function instanceOfPaginatedGenericParameterList(value: object): value is PaginatedGenericParameterList {
    return true;
}

export function PaginatedGenericParameterListFromJSON(json: any): PaginatedGenericParameterList {
    return PaginatedGenericParameterListFromJSONTyped(json, false);
}

export function PaginatedGenericParameterListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedGenericParameterList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(GenericParameterFromJSON)),
    };
}

export function PaginatedGenericParameterListToJSON(value?: PaginatedGenericParameterList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(GenericParameterToJSON)),
    };
}

