/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileDownloadToken } from './FileDownloadToken';
import {
    FileDownloadTokenFromJSON,
    FileDownloadTokenFromJSONTyped,
    FileDownloadTokenToJSON,
} from './FileDownloadToken';

/**
 * 
 * @export
 * @interface PaginatedFileDownloadTokenList
 */
export interface PaginatedFileDownloadTokenList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedFileDownloadTokenList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedFileDownloadTokenList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedFileDownloadTokenList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<FileDownloadToken>}
     * @memberof PaginatedFileDownloadTokenList
     */
    results?: Array<FileDownloadToken>;
}

/**
 * Check if a given object implements the PaginatedFileDownloadTokenList interface.
 */
export function instanceOfPaginatedFileDownloadTokenList(value: object): value is PaginatedFileDownloadTokenList {
    return true;
}

export function PaginatedFileDownloadTokenListFromJSON(json: any): PaginatedFileDownloadTokenList {
    return PaginatedFileDownloadTokenListFromJSONTyped(json, false);
}

export function PaginatedFileDownloadTokenListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedFileDownloadTokenList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(FileDownloadTokenFromJSON)),
    };
}

export function PaginatedFileDownloadTokenListToJSON(value?: PaginatedFileDownloadTokenList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(FileDownloadTokenToJSON)),
    };
}

