/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PipelineSourceFile } from './PipelineSourceFile';
import {
    PipelineSourceFileFromJSON,
    PipelineSourceFileFromJSONTyped,
    PipelineSourceFileToJSON,
} from './PipelineSourceFile';

/**
 * 
 * @export
 * @interface PaginatedPipelineSourceFileList
 */
export interface PaginatedPipelineSourceFileList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedPipelineSourceFileList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPipelineSourceFileList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPipelineSourceFileList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<PipelineSourceFile>}
     * @memberof PaginatedPipelineSourceFileList
     */
    results?: Array<PipelineSourceFile>;
}

/**
 * Check if a given object implements the PaginatedPipelineSourceFileList interface.
 */
export function instanceOfPaginatedPipelineSourceFileList(value: object): value is PaginatedPipelineSourceFileList {
    return true;
}

export function PaginatedPipelineSourceFileListFromJSON(json: any): PaginatedPipelineSourceFileList {
    return PaginatedPipelineSourceFileListFromJSONTyped(json, false);
}

export function PaginatedPipelineSourceFileListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedPipelineSourceFileList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(PipelineSourceFileFromJSON)),
    };
}

export function PaginatedPipelineSourceFileListToJSON(value?: PaginatedPipelineSourceFileList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(PipelineSourceFileToJSON)),
    };
}

