/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileBrowserFolderGroupPermission } from './FileBrowserFolderGroupPermission';
import {
    FileBrowserFolderGroupPermissionFromJSON,
    FileBrowserFolderGroupPermissionFromJSONTyped,
    FileBrowserFolderGroupPermissionToJSON,
} from './FileBrowserFolderGroupPermission';

/**
 * 
 * @export
 * @interface PaginatedFileBrowserFolderGroupPermissionList
 */
export interface PaginatedFileBrowserFolderGroupPermissionList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedFileBrowserFolderGroupPermissionList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedFileBrowserFolderGroupPermissionList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedFileBrowserFolderGroupPermissionList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<FileBrowserFolderGroupPermission>}
     * @memberof PaginatedFileBrowserFolderGroupPermissionList
     */
    results?: Array<FileBrowserFolderGroupPermission>;
}

/**
 * Check if a given object implements the PaginatedFileBrowserFolderGroupPermissionList interface.
 */
export function instanceOfPaginatedFileBrowserFolderGroupPermissionList(value: object): value is PaginatedFileBrowserFolderGroupPermissionList {
    return true;
}

export function PaginatedFileBrowserFolderGroupPermissionListFromJSON(json: any): PaginatedFileBrowserFolderGroupPermissionList {
    return PaginatedFileBrowserFolderGroupPermissionListFromJSONTyped(json, false);
}

export function PaginatedFileBrowserFolderGroupPermissionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedFileBrowserFolderGroupPermissionList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(FileBrowserFolderGroupPermissionFromJSON)),
    };
}

export function PaginatedFileBrowserFolderGroupPermissionListToJSON(value?: PaginatedFileBrowserFolderGroupPermissionList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(FileBrowserFolderGroupPermissionToJSON)),
    };
}

