/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileBrowserFileUserPermission } from './FileBrowserFileUserPermission';
import {
    FileBrowserFileUserPermissionFromJSON,
    FileBrowserFileUserPermissionFromJSONTyped,
    FileBrowserFileUserPermissionToJSON,
} from './FileBrowserFileUserPermission';

/**
 * 
 * @export
 * @interface PaginatedFileBrowserFileUserPermissionList
 */
export interface PaginatedFileBrowserFileUserPermissionList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedFileBrowserFileUserPermissionList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedFileBrowserFileUserPermissionList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedFileBrowserFileUserPermissionList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<FileBrowserFileUserPermission>}
     * @memberof PaginatedFileBrowserFileUserPermissionList
     */
    results?: Array<FileBrowserFileUserPermission>;
}

/**
 * Check if a given object implements the PaginatedFileBrowserFileUserPermissionList interface.
 */
export function instanceOfPaginatedFileBrowserFileUserPermissionList(value: object): value is PaginatedFileBrowserFileUserPermissionList {
    return true;
}

export function PaginatedFileBrowserFileUserPermissionListFromJSON(json: any): PaginatedFileBrowserFileUserPermissionList {
    return PaginatedFileBrowserFileUserPermissionListFromJSONTyped(json, false);
}

export function PaginatedFileBrowserFileUserPermissionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedFileBrowserFileUserPermissionList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(FileBrowserFileUserPermissionFromJSON)),
    };
}

export function PaginatedFileBrowserFileUserPermissionListToJSON(value?: PaginatedFileBrowserFileUserPermissionList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(FileBrowserFileUserPermissionToJSON)),
    };
}

