/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PluginPiping } from './PluginPiping';
import {
    PluginPipingFromJSON,
    PluginPipingFromJSONTyped,
    PluginPipingToJSON,
} from './PluginPiping';

/**
 * 
 * @export
 * @interface PaginatedPluginPipingList
 */
export interface PaginatedPluginPipingList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedPluginPipingList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPluginPipingList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPluginPipingList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<PluginPiping>}
     * @memberof PaginatedPluginPipingList
     */
    results?: Array<PluginPiping>;
}

/**
 * Check if a given object implements the PaginatedPluginPipingList interface.
 */
export function instanceOfPaginatedPluginPipingList(value: object): value is PaginatedPluginPipingList {
    return true;
}

export function PaginatedPluginPipingListFromJSON(json: any): PaginatedPluginPipingList {
    return PaginatedPluginPipingListFromJSONTyped(json, false);
}

export function PaginatedPluginPipingListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedPluginPipingList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(PluginPipingFromJSON)),
    };
}

export function PaginatedPluginPipingListToJSON(value?: PaginatedPluginPipingList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(PluginPipingToJSON)),
    };
}

