/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `r` - Read
 * * `w` - Write
 * @export
 */
export const PermissionEnum = {
    R: 'r',
    W: 'w'
} as const;
export type PermissionEnum = typeof PermissionEnum[keyof typeof PermissionEnum];


export function instanceOfPermissionEnum(value: any): boolean {
    for (const key in PermissionEnum) {
        if (Object.prototype.hasOwnProperty.call(PermissionEnum, key)) {
            if (PermissionEnum[key as keyof typeof PermissionEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PermissionEnumFromJSON(json: any): PermissionEnum {
    return PermissionEnumFromJSONTyped(json, false);
}

export function PermissionEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionEnum {
    return json as PermissionEnum;
}

export function PermissionEnumToJSON(value?: PermissionEnum | null): any {
    return value as any;
}

