/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BlankEnum } from './BlankEnum';
import {
    instanceOfBlankEnum,
    BlankEnumFromJSON,
    BlankEnumFromJSONTyped,
    BlankEnumToJSON,
} from './BlankEnum';
import type { FtypeEnum } from './FtypeEnum';
import {
    instanceOfFtypeEnum,
    FtypeEnumFromJSON,
    FtypeEnumFromJSONTyped,
    FtypeEnumToJSON,
} from './FtypeEnum';

/**
 * @type PipelineSourceFileFtype
 * 
 * @export
 */
export type PipelineSourceFileFtype = BlankEnum | FtypeEnum;

export function PipelineSourceFileFtypeFromJSON(json: any): PipelineSourceFileFtype {
    return PipelineSourceFileFtypeFromJSONTyped(json, false);
}

export function PipelineSourceFileFtypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelineSourceFileFtype {
    if (json == null) {
        return json;
    }
    if (instanceOfBlankEnum(json)) {
        return BlankEnumFromJSONTyped(json, true);
    }
    if (instanceOfFtypeEnum(json)) {
        return FtypeEnumFromJSONTyped(json, true);
    }

    return {} as any;
}

export function PipelineSourceFileFtypeToJSON(value?: PipelineSourceFileFtype | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfBlankEnum(value)) {
        return BlankEnumToJSON(value as BlankEnum);
    }
    if (instanceOfFtypeEnum(value)) {
        return FtypeEnumToJSON(value as FtypeEnum);
    }

    return {};
}

