/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PipelineSourceFileFtype } from './PipelineSourceFileFtype';
import {
    PipelineSourceFileFtypeFromJSON,
    PipelineSourceFileFtypeFromJSONTyped,
    PipelineSourceFileFtypeToJSON,
} from './PipelineSourceFileFtype';

/**
 * 
 * @export
 * @interface PipelineSourceFile
 */
export interface PipelineSourceFile {
    /**
     * 
     * @type {string}
     * @memberof PipelineSourceFile
     */
    readonly url: string;
    /**
     * 
     * @type {number}
     * @memberof PipelineSourceFile
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof PipelineSourceFile
     */
    readonly creationDate: Date;
    /**
     * 
     * @type {string}
     * @memberof PipelineSourceFile
     */
    fname: string;
    /**
     * 
     * @type {string}
     * @memberof PipelineSourceFile
     */
    readonly fsize: string;
    /**
     * 
     * @type {boolean}
     * @memberof PipelineSourceFile
     */
    _public?: boolean;
    /**
     * 
     * @type {PipelineSourceFileFtype}
     * @memberof PipelineSourceFile
     */
    ftype: PipelineSourceFileFtype;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof PipelineSourceFile
     */
    readonly uploaderUsername: string;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof PipelineSourceFile
     */
    readonly ownerUsername: string;
    /**
     * 
     * @type {number}
     * @memberof PipelineSourceFile
     */
    readonly pipelineId: number;
    /**
     * 
     * @type {string}
     * @memberof PipelineSourceFile
     */
    readonly pipelineName: string;
    /**
     * 
     * @type {string}
     * @memberof PipelineSourceFile
     */
    readonly fileResource: string;
    /**
     * 
     * @type {string}
     * @memberof PipelineSourceFile
     */
    readonly parentFolder: string;
    /**
     * 
     * @type {string}
     * @memberof PipelineSourceFile
     */
    readonly owner: string;
}

/**
 * Check if a given object implements the PipelineSourceFile interface.
 */
export function instanceOfPipelineSourceFile(value: object): value is PipelineSourceFile {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('creationDate' in value) || value['creationDate'] === undefined) return false;
    if (!('fname' in value) || value['fname'] === undefined) return false;
    if (!('fsize' in value) || value['fsize'] === undefined) return false;
    if (!('ftype' in value) || value['ftype'] === undefined) return false;
    if (!('uploaderUsername' in value) || value['uploaderUsername'] === undefined) return false;
    if (!('ownerUsername' in value) || value['ownerUsername'] === undefined) return false;
    if (!('pipelineId' in value) || value['pipelineId'] === undefined) return false;
    if (!('pipelineName' in value) || value['pipelineName'] === undefined) return false;
    if (!('fileResource' in value) || value['fileResource'] === undefined) return false;
    if (!('parentFolder' in value) || value['parentFolder'] === undefined) return false;
    if (!('owner' in value) || value['owner'] === undefined) return false;
    return true;
}

export function PipelineSourceFileFromJSON(json: any): PipelineSourceFile {
    return PipelineSourceFileFromJSONTyped(json, false);
}

export function PipelineSourceFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelineSourceFile {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'id': json['id'],
        'creationDate': (new Date(json['creation_date'])),
        'fname': json['fname'],
        'fsize': json['fsize'],
        '_public': json['public'] == null ? undefined : json['public'],
        'ftype': PipelineSourceFileFtypeFromJSON(json['ftype']),
        'uploaderUsername': json['uploader_username'],
        'ownerUsername': json['owner_username'],
        'pipelineId': json['pipeline_id'],
        'pipelineName': json['pipeline_name'],
        'fileResource': json['file_resource'],
        'parentFolder': json['parent_folder'],
        'owner': json['owner'],
    };
}

export function PipelineSourceFileToJSON(value?: Omit<PipelineSourceFile, 'url'|'id'|'creation_date'|'fsize'|'uploader_username'|'owner_username'|'pipeline_id'|'pipeline_name'|'file_resource'|'parent_folder'|'owner'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'fname': value['fname'],
        'public': value['_public'],
        'ftype': PipelineSourceFileFtypeToJSON(value['ftype']),
    };
}

