/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PluginInstanceSplitRequest
 */
export interface PluginInstanceSplitRequest {
    /**
     * 
     * @type {string}
     * @memberof PluginInstanceSplitRequest
     */
    filter?: string;
    /**
     * 
     * @type {string}
     * @memberof PluginInstanceSplitRequest
     */
    computeResourceName?: string;
}

/**
 * Check if a given object implements the PluginInstanceSplitRequest interface.
 */
export function instanceOfPluginInstanceSplitRequest(value: object): value is PluginInstanceSplitRequest {
    return true;
}

export function PluginInstanceSplitRequestFromJSON(json: any): PluginInstanceSplitRequest {
    return PluginInstanceSplitRequestFromJSONTyped(json, false);
}

export function PluginInstanceSplitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginInstanceSplitRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'filter': json['filter'] == null ? undefined : json['filter'],
        'computeResourceName': json['compute_resource_name'] == null ? undefined : json['compute_resource_name'],
    };
}

export function PluginInstanceSplitRequestToJSON(value?: PluginInstanceSplitRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'filter': value['filter'],
        'compute_resource_name': value['computeResourceName'],
    };
}

