/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Tag
 */
export interface Tag {
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    readonly url: string;
    /**
     * 
     * @type {number}
     * @memberof Tag
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    name?: string;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof Tag
     */
    readonly ownerUsername: string;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    color: string;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    readonly feeds: string;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    readonly taggings: string;
}

/**
 * Check if a given object implements the Tag interface.
 */
export function instanceOfTag(value: object): value is Tag {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ownerUsername' in value) || value['ownerUsername'] === undefined) return false;
    if (!('color' in value) || value['color'] === undefined) return false;
    if (!('feeds' in value) || value['feeds'] === undefined) return false;
    if (!('taggings' in value) || value['taggings'] === undefined) return false;
    return true;
}

export function TagFromJSON(json: any): Tag {
    return TagFromJSONTyped(json, false);
}

export function TagFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tag {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'ownerUsername': json['owner_username'],
        'color': json['color'],
        'feeds': json['feeds'],
        'taggings': json['taggings'],
    };
}

export function TagToJSON(value?: Omit<Tag, 'url'|'id'|'owner_username'|'feeds'|'taggings'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'color': value['color'],
    };
}

