/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Tagging
 */
export interface Tagging {
    /**
     * 
     * @type {string}
     * @memberof Tagging
     */
    readonly url: string;
    /**
     * 
     * @type {number}
     * @memberof Tagging
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof Tagging
     */
    readonly tagId: number;
    /**
     * 
     * @type {number}
     * @memberof Tagging
     */
    readonly feedId: number;
    /**
     * 
     * @type {string}
     * @memberof Tagging
     */
    readonly tag: string;
    /**
     * 
     * @type {string}
     * @memberof Tagging
     */
    readonly feed: string;
}

/**
 * Check if a given object implements the Tagging interface.
 */
export function instanceOfTagging(value: object): value is Tagging {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tagId' in value) || value['tagId'] === undefined) return false;
    if (!('feedId' in value) || value['feedId'] === undefined) return false;
    if (!('tag' in value) || value['tag'] === undefined) return false;
    if (!('feed' in value) || value['feed'] === undefined) return false;
    return true;
}

export function TaggingFromJSON(json: any): Tagging {
    return TaggingFromJSONTyped(json, false);
}

export function TaggingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tagging {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'id': json['id'],
        'tagId': json['tag_id'],
        'feedId': json['feed_id'],
        'tag': json['tag'],
        'feed': json['feed'],
    };
}

export function TaggingToJSON(value?: Omit<Tagging, 'url'|'id'|'tag_id'|'feed_id'|'tag'|'feed'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
    };
}

