/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `ds` - Data synthesis
 * * `fs` - Feed synthesis
 * * `ts` - Topology synthesis
 * @export
 */
export const Type4beEnum = {
    Ds: 'ds',
    Fs: 'fs',
    Ts: 'ts'
} as const;
export type Type4beEnum = typeof Type4beEnum[keyof typeof Type4beEnum];


export function instanceOfType4beEnum(value: any): boolean {
    for (const key in Type4beEnum) {
        if (Object.prototype.hasOwnProperty.call(Type4beEnum, key)) {
            if (Type4beEnum[key as keyof typeof Type4beEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function Type4beEnumFromJSON(json: any): Type4beEnum {
    return Type4beEnumFromJSONTyped(json, false);
}

export function Type4beEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): Type4beEnum {
    return json as Type4beEnum;
}

export function Type4beEnumToJSON(value?: Type4beEnum | null): any {
    return value as any;
}

