/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserFileRequest
 */
export interface UserFileRequest {
    /**
     * 
     * @type {string}
     * @memberof UserFileRequest
     */
    uploadPath?: string;
    /**
     * 
     * @type {Blob}
     * @memberof UserFileRequest
     */
    fname?: Blob;
    /**
     * 
     * @type {boolean}
     * @memberof UserFileRequest
     */
    _public?: boolean;
}

/**
 * Check if a given object implements the UserFileRequest interface.
 */
export function instanceOfUserFileRequest(value: object): value is UserFileRequest {
    return true;
}

export function UserFileRequestFromJSON(json: any): UserFileRequest {
    return UserFileRequestFromJSONTyped(json, false);
}

export function UserFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'uploadPath': json['upload_path'] == null ? undefined : json['upload_path'],
        'fname': json['fname'] == null ? undefined : json['fname'],
        '_public': json['public'] == null ? undefined : json['public'],
    };
}

export function UserFileRequestToJSON(value?: UserFileRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'upload_path': value['uploadPath'],
        'fname': value['fname'],
        'public': value['_public'],
    };
}

