/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkflowRequest
 */
export interface WorkflowRequest {
    /**
     * 
     * @type {string}
     * @memberof WorkflowRequest
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof WorkflowRequest
     */
    previousPluginInstId?: number;
    /**
     * 
     * @type {any}
     * @memberof WorkflowRequest
     */
    nodesInfo?: any | null;
}

/**
 * Check if a given object implements the WorkflowRequest interface.
 */
export function instanceOfWorkflowRequest(value: object): value is WorkflowRequest {
    return true;
}

export function WorkflowRequestFromJSON(json: any): WorkflowRequest {
    return WorkflowRequestFromJSONTyped(json, false);
}

export function WorkflowRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'previousPluginInstId': json['previous_plugin_inst_id'] == null ? undefined : json['previous_plugin_inst_id'],
        'nodesInfo': json['nodes_info'] == null ? undefined : json['nodes_info'],
    };
}

export function WorkflowRequestToJSON(value?: WorkflowRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'previous_plugin_inst_id': value['previousPluginInstId'],
        'nodes_info': value['nodesInfo'],
    };
}

