/* tslint:disable */
/* eslint-disable */
/**
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 0.0.0+unknown
 * Contact: dev@babymri.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Feed,
  FeedRequest,
  PaginatedFeedList,
} from '../models/index';
import {
    FeedFromJSON,
    FeedToJSON,
    FeedRequestFromJSON,
    FeedRequestToJSON,
    PaginatedFeedListFromJSON,
    PaginatedFeedListToJSON,
} from '../models/index';

export interface RootDestroyRequest {
    id: number;
    format?: RootDestroyFormatEnum;
}

export interface RootListRequest {
    format?: RootListFormatEnum;
    limit?: number;
    offset?: number;
}

export interface RootRetrieveRequest {
    id: number;
    format?: RootRetrieveFormatEnum;
}

export interface RootUpdateRequest {
    id: number;
    format?: RootUpdateFormatEnum;
    feedRequest?: FeedRequest;
}

/**
 * DefaultApi - interface
 * 
 * @export
 * @interface DefaultApiInterface
 */
export interface DefaultApiInterface {
    /**
     * A feed view.
     * @param {number} id 
     * @param {'collection+json' | 'json'} [format] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    rootDestroyRaw(requestParameters: RootDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * A feed view.
     */
    rootDestroy(requestParameters: RootDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * A view for the collection of feeds. This is also the API\'s \"homepage\".
     * @param {'collection+json' | 'json'} [format] 
     * @param {number} [limit] Number of results to return per page.
     * @param {number} [offset] The initial index from which to return the results.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    rootListRaw(requestParameters: RootListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedFeedList>>;

    /**
     * A view for the collection of feeds. This is also the API\'s \"homepage\".
     */
    rootList(requestParameters: RootListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedFeedList>;

    /**
     * A feed view.
     * @param {number} id 
     * @param {'collection+json' | 'json'} [format] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    rootRetrieveRaw(requestParameters: RootRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Feed>>;

    /**
     * A feed view.
     */
    rootRetrieve(requestParameters: RootRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Feed>;

    /**
     * A feed view.
     * @param {number} id 
     * @param {'collection+json' | 'json'} [format] 
     * @param {FeedRequest} [feedRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    rootUpdateRaw(requestParameters: RootUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Feed>>;

    /**
     * A feed view.
     */
    rootUpdate(requestParameters: RootUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Feed>;

}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI implements DefaultApiInterface {

    /**
     * A feed view.
     */
    async rootDestroyRaw(requestParameters: RootDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling rootDestroy().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {Accept: 'application/json'};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        const response = await this.request({
            path: `/api/v1/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * A feed view.
     */
    async rootDestroy(requestParameters: RootDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.rootDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * A view for the collection of feeds. This is also the API\'s \"homepage\".
     */
    async rootListRaw(requestParameters: RootListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedFeedList>> {
        const queryParameters: any = {};

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {Accept: 'application/json'};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        const response = await this.request({
            path: `/api/v1/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedFeedListFromJSON(jsonValue));
    }

    /**
     * A view for the collection of feeds. This is also the API\'s \"homepage\".
     */
    async rootList(requestParameters: RootListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedFeedList> {
        const response = await this.rootListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * A feed view.
     */
    async rootRetrieveRaw(requestParameters: RootRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Feed>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling rootRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {Accept: 'application/json'};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        const response = await this.request({
            path: `/api/v1/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FeedFromJSON(jsonValue));
    }

    /**
     * A feed view.
     */
    async rootRetrieve(requestParameters: RootRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Feed> {
        const response = await this.rootRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * A feed view.
     */
    async rootUpdateRaw(requestParameters: RootUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Feed>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling rootUpdate().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {Accept: 'application/json'};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        const response = await this.request({
            path: `/api/v1/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: FeedRequestToJSON(requestParameters['feedRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FeedFromJSON(jsonValue));
    }

    /**
     * A feed view.
     */
    async rootUpdate(requestParameters: RootUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Feed> {
        const response = await this.rootUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const RootDestroyFormatEnum = {
    Collectionjson: 'collection+json',
    Json: 'json'
} as const;
export type RootDestroyFormatEnum = typeof RootDestroyFormatEnum[keyof typeof RootDestroyFormatEnum];
/**
 * @export
 */
export const RootListFormatEnum = {
    Collectionjson: 'collection+json',
    Json: 'json'
} as const;
export type RootListFormatEnum = typeof RootListFormatEnum[keyof typeof RootListFormatEnum];
/**
 * @export
 */
export const RootRetrieveFormatEnum = {
    Collectionjson: 'collection+json',
    Json: 'json'
} as const;
export type RootRetrieveFormatEnum = typeof RootRetrieveFormatEnum[keyof typeof RootRetrieveFormatEnum];
/**
 * @export
 */
export const RootUpdateFormatEnum = {
    Collectionjson: 'collection+json',
    Json: 'json'
} as const;
export type RootUpdateFormatEnum = typeof RootUpdateFormatEnum[keyof typeof RootUpdateFormatEnum];
